server {
  listen 80;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  # Proxy to Service A
  location /servicea/ {
    proxy_pass http://servicea:3001/;
  }

  # Proxy to Service B
  location /serviceb/ {
    proxy_pass http://serviceb:3002/;
  }

  # Proxy to Service C
  location /servicec/ {
    proxy_pass http://servicec:3003/;
  }

  # Proxy to Service D
  location /serviced/ {
    proxy_pass http://serviced:3004/;
  }

  # Proxy to Service E
  location /servicee/ {
    proxy_pass http://servicee:3005/;
  }
}